### PR TITLE
Improve orb metadata

### PR DESCRIPTION
**Pull request by mcafaro**
CircleCI recommended we expand our current orb description, shown below, to help with SEO:

https://github.com/mathworks/matlab-circleci-orb/blob/14a5dd9b1aa29f32cd8965a0199ffdeb8d64f6da/src/%40orb.yml#L4

@mw-hrastega and @asifouna can you help? This is the description that shows at the top of the [orb page](https://circleci.com/orbs/registry/orb/mathworks/matlab):

desc

Maybe some words to include: MBD, toolboxes, MEX, scripts, models?

I'm also wondering if perhaps we should be more forward looking with this line:

https://github.com/mathworks/matlab-circleci-orb/blob/2b939a70928e87d86e49512d4db543c3d079fdce/src/commands/install.yml#L2-L3

And say something like "Currently, this command is only available for public projects."?

### CODE REVIEW

**Comment by acampbel** [comment]
> CircleCI recommended we expand our current orb description, shown below, to help with SEO:
> 
> https://github.com/mathworks/matlab-circleci-orb/blob/14a5dd9b1aa29f32cd8965a0199ffdeb8d64f6da/src/%40orb.yml#L4
> 
> @mw-hrastega and @asifouna can you help? This is the description that shows at the top of the [orb page](https://circleci.com/orbs/registry/orb/mathworks/matlab):
> 
> desc
> 
> Maybe some words to include: MBD, toolboxes, MEX, scripts, models?
> 
> I'm also wondering if perhaps we should be more forward looking with this line:
> 
> https://github.com/mathworks/matlab-circleci-orb/blob/2b939a70928e87d86e49512d4db543c3d079fdce/src/commands/install.yml#L2-L3
> 
> And say something like "Currently, this command is only available for public projects."?

I like your suggestion on rephrasing the public support.

**Comment by mw-hrastega** [comment]
RE: Orb description: Run MATLAB and Simulink as part of your build pipeline. 

How about something like this?

This orb enables you to run MATLAB scripts, functions, and statements as part of your build pipeline. You also can run your MATLAB and Simulink tests, generate artifacts, and publish your results to CircleCI.

or

Run MATLAB scripts, functions, and statements as part of your build pipeline. Additionally, run your MATLAB and Simulink tests, generate artifacts, and publish your results to CircleCI.
*********************************************************************
RE: "Currently, this command is only available for public projects."
I would place "only" after available: Currently, this command is available only for public projects.

**Comment by mcafaro** [comment]
> Run MATLAB scripts, functions, and statements as part of your build pipeline. Additionally, run your MATLAB and Simulink tests, generate artifacts, and publish your results to CircleCI.

Thanks @mw-hrastega. I like this, although I think it might be important to get Simulink in the first few words because they are the only words you see while exploring orbs. See https://circleci.com/orbs/registry/

How about:

Run MATLAB and Simulink as part of your build pipeline. Test and verify code and models, build MEX files, and package toolboxes or libraries for deployment.

**Comment by mw-hrastega** [comment]
Thanks @mcafaro. Good point. Your proposal sounds good. I am just not sure if the orb currently supports packaging toolboxes, etc. If it does, then the text is fine.

I also have another idea: 
"Run MATLAB and Simulink as part of your build pipeline, test code and model, generate artifacts, and publish your results to CircleCI."

or

"Run MATLAB and Simulink as part of your build pipeline, generate test artifacts, and publish your results to CircleCI."

**Comment by mcafaro** [comment]
> "Run MATLAB and Simulink as part of your build pipeline, test code and model, generate artifacts, and publish your results to CircleCI."

Love this.

**Comment by asifouna** [comment]
> > "Run MATLAB and Simulink as part of your build pipeline, test code and model, generate artifacts, and publish your results to CircleCI."
> 
> Love this.

In this sentence, "run test and model" sounds very strange to me.

How about:

"Run MATLAB code and Simulink models as part of your build pipeline, execute tests, generate artifacts, and publish your results to CircleCI."

**Comment by mcafaro** [comment]
@asifouna it is now:

Test MATLAB code and Simulink models, generate artifacts, and publish your results.

Sound better?

**Comment by asifouna** [comment]
> @asifouna it is now:
> 
> Test MATLAB code and Simulink models, generate artifacts, and publish your results.
> 
> Sound better?

Sounds good to me!

**Comment by mcafaro** [comment]
Thanks all. In the end we're back to "Run MATLAB and Simulink as part of your build pipeline" because it has a nice generality to it and still keeps the words MATLAB and Simulink front-and-center.

The `install` command description was also updated per @asifouna's request.

**Pull request merged**
